# -*- coding: utf-8 -*-
"""DML TASK1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wjqoWXflkNr6Fkv2zXPT0Ur0u9ptFq5X

**Deep Learning CNN for Fashion-MNIST Clothing Classification**
"""

#.Deep Learning CNN for Fashion-MNIST Clothing Classification
#The Fashion-MNIST clothing classification problem is a new standard dataset used in
#computer vision and deep learning.

!wget https://github.com/zalandoresearch/fashion-mnist

from tensorflow.keras.datasets import fashion_mnist
import matplotlib.pyplot as plt
(train_images,train_labels),(test_images,test_labels)=fashion_mnist.load_data()
print("Training images shape:",train_images.shape)
print("Training labels shape:",train_labels.shape)
print("Test images shape:",test_images.shape)
print("Test labels shape:",test_labels.shape)
class_names=['T-shirt/top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag',
             'Ankle boot']
plt.figure()
plt.imshow(train_images[0],cmap='gray')
plt.colorbar()
plt.grid(False)
plt.title(f"Class:{class_names[train_labels[0]]}")
plt.show()